#!/bin/bash -eu

ln -s $PWD/.config/zsh ~/.config/zsh
ln -s $PWD/.zshrc ~/.zshrc
ln -s $PWD/.zshrc-custo ~/.zshrc-custo
mkdir -p ~/.zsh
pushd ~/.zsh
git git clone https://github.com/marlonrichert/zsh-snap.git

chsh -s $(which zsh)
echo 'Restart your shell and run `znap pull`'
